FROM node:22-alpine as builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

# Recibir las variables de entorno de CapRover en build time
ARG VITE_API_BASE_URL=${VITE_API_BASE_URL}
ARG VITE_N8N_API_BASE_URL=${VITE_N8N_API_BASE_URL}
ARG VITE_GRAPHHOPPER_URL=${VITE_GRAPHHOPPER_URL}
ARG VITE_GRAPHHOPPER_API_KEY=${VITE_GRAPHHOPPER_API_KEY}

ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}
ENV VITE_N8N_API_BASE_URL=${VITE_N8N_API_BASE_URL}
ENV VITE_GRAPHHOPPER_URL=${VITE_GRAPHHOPPER_URL}
ENV VITE_GRAPHHOPPER_API_KEY=${VITE_GRAPHHOPPER_API_KEY}

RUN npm run build

FROM nginx:alpine as production

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
